<a href="https://colab.research.google.com/github/Aris-27/Machine-Learning/blob/main/MachineLearning3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Rivo Aris M

240210005

In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, BaggingClassifier, ExtraTreesClassifier, AdaBoostClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import confusion_matrix, classification_report

In [82]:
df = pd.read_csv('/content/Modelling.csv.xls')

In [83]:
df.head(10)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0

In [84]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [85]:
df.isna().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [86]:
print (f'Duplicated values:{df.duplicated().sum()}')

Duplicated values:0

In [87]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [88]:
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'])
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [90]:
encoder = LabelEncoder()
df['Geography'] = encoder.fit_transform(df['Geography'])
df['Gender'] = encoder.fit_transform(df['Gender'])

In [91]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,0,0,42,2,0.00,1,1,1,101348.88,1
1,608,2,0,41,1,83807.86,1,0,1,112542.58,0
2,502,0,0,42,8,159660.80,3,1,0,113931.57,1
3,699,0,0,39,1,0.00,2,0,0,93826.63,0
4,850,2,0,43,2,125510.82,1,1,1,79084.10,0

In [92]:
x = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [93]:
x

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,0,0,42,2,0.00,1,1,1,101348.88
1,608,2,0,41,1,83807.86,1,0,1,112542.58
2,502,0,0,42,8,159660.80,3,1,0,113931.57
3,699,0,0,39,1,0.00,2,0,0,93826.63
4,850,2,0,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,0,1,39,5,0.00,2,1,0,96270.64
9996,516,0,1,35,10,57369.61,1,1,1,101699.77
9997,709,0,0,36,7,0.00,1,0,1,42085.58
9998,772,1,1,42,3,75075.31,2,1,0,92888.52
9999,792,0,0,28,4,130142.79,1,1,0,38190.78

In [94]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [95]:
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [96]:
x

array([[0.538     , 0.        , 0.        , ..., 1.        , 1.        ,
        0.50673489],
       [0.516     , 1.        , 0.        , ..., 0.        , 1.        ,
        0.56270874],
       [0.304     , 0.        , 0.        , ..., 1.        , 0.        ,
        0.56965435],
       ...,
       [0.718     , 0.        , 0.        , ..., 0.        , 1.        ,
        0.21039009],
       [0.844     , 0.5       , 1.        , ..., 1.        , 0.        ,
        0.46442905],
       [0.884     , 0.        , 0.        , ..., 1.        , 0.        ,
        0.19091423]])

In [97]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [98]:
from ast import mod
model_1 = LogisticRegression()
model_2 = SVC()
model_3 = KNeighborsClassifier()
model_4 = DecisionTreeClassifier()
model_5 = RandomForestClassifier()
model_6 = BaggingClassifier()
model_7 = ExtraTreesClassifier()
model_8 = AdaBoostClassifier()
model_9 = XGBClassifier()
model_10 = CatBoostClassifier()
model_11 = LGBMClassifier()

In [99]:
model_1.fit(x_train, y_train)

LogisticRegression()

In [100]:
y_pred = model_1.predict(x_test)

In [101]:
print(confusion_matrix(y_test, y_pred))

[[1565   42]
 [ 326   67]]

In [102]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.97      0.89      1607
           1       0.61      0.17      0.27       393

    accuracy                           0.82      2000
   macro avg       0.72      0.57      0.58      2000
weighted avg       0.79      0.82      0.77      2000

In [103]:
model_2.fit(x_train, y_train)

SVC()

In [104]:
y_pred = model_2.predict(x_test)

In [105]:
print(confusion_matrix(y_test, y_pred))

[[1581   26]
 [ 268  125]]

In [106]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.86      0.98      0.91      1607
           1       0.83      0.32      0.46       393

    accuracy                           0.85      2000
   macro avg       0.84      0.65      0.69      2000
weighted avg       0.85      0.85      0.83      2000

In [107]:
model_3.fit(x_train, y_train)

KNeighborsClassifier()

In [108]:
y_pred = model_3.predict(x_test)

In [109]:
print(confusion_matrix(y_test, y_pred))

[[1520   87]
 [ 265  128]]

In [110]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.95      0.90      1607
           1       0.60      0.33      0.42       393

    accuracy                           0.82      2000
   macro avg       0.72      0.64      0.66      2000
weighted avg       0.80      0.82      0.80      2000

In [111]:
model_4.fit(x_train, y_train)

DecisionTreeClassifier()

In [112]:
y_pred = model_4.predict(x_test)

In [113]:
print(confusion_matrix(y_test, y_pred))

[[1371  236]
 [ 189  204]]

In [114]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.85      0.87      1607
           1       0.46      0.52      0.49       393

    accuracy                           0.79      2000
   macro avg       0.67      0.69      0.68      2000
weighted avg       0.80      0.79      0.79      2000

In [115]:
model_5.fit(x_train, y_train)

RandomForestClassifier()

In [116]:
y_pred = model_5.predict(x_test)

In [117]:
print(confusion_matrix(y_test, y_pred))

[[1552   55]
 [ 208  185]]

In [118]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.77      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.83      0.72      0.75      2000
weighted avg       0.86      0.87      0.86      2000

In [119]:
model_6.fit(x_train, y_train)

BaggingClassifier()

In [120]:
y_pred = model_6.predict(x_test)

In [121]:
print(confusion_matrix(y_test, y_pred))

[[1529   78]
 [ 205  188]]

In [122]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1607
           1       0.71      0.48      0.57       393

    accuracy                           0.86      2000
   macro avg       0.79      0.71      0.74      2000
weighted avg       0.85      0.86      0.85      2000

In [123]:
model_7.fit(x_train, y_train)

ExtraTreesClassifier()

In [124]:
y_pred = model_7.predict(x_test)

In [125]:
print(confusion_matrix(y_test, y_pred))

[[1551   56]
 [ 210  183]]

In [126]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.97      0.92      1607
           1       0.77      0.47      0.58       393

    accuracy                           0.87      2000
   macro avg       0.82      0.72      0.75      2000
weighted avg       0.86      0.87      0.85      2000

In [127]:
model_8.fit(x_train, y_train)

AdaBoostClassifier()

In [128]:
y_pred = model_8.predict(x_test)

In [129]:
print(confusion_matrix(y_test, y_pred))

[[1541   66]
 [ 218  175]]

In [130]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1607
           1       0.73      0.45      0.55       393

    accuracy                           0.86      2000
   macro avg       0.80      0.70      0.73      2000
weighted avg       0.85      0.86      0.84      2000

In [131]:
model_9.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [132]:
y_pred = model_9.predict(x_test)

In [133]:
print(confusion_matrix(y_test, y_pred))

[[1517   90]
 [ 199  194]]

In [134]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.94      0.91      1607
           1       0.68      0.49      0.57       393

    accuracy                           0.86      2000
   macro avg       0.78      0.72      0.74      2000
weighted avg       0.84      0.86      0.85      2000

In [135]:
model_10.fit(x_train, y_train)

Learning rate set to 0.025035
0:	learn: 0.6724181	total: 3.95ms	remaining: 3.95s
1:	learn: 0.6530928	total: 7.14ms	remaining: 3.56s
2:	learn: 0.6357871	total: 10.3ms	remaining: 3.43s
3:	learn: 0.6176962	total: 13.9ms	remaining: 3.46s
4:	learn: 0.6011385	total: 17.2ms	remaining: 3.41s
5:	learn: 0.5860065	total: 20.7ms	remaining: 3.43s
6:	learn: 0.5717487	total: 24ms	remaining: 3.4s
7:	learn: 0.5584128	total: 27.3ms	remaining: 3.38s
8:	learn: 0.5468963	total: 30.8ms	remaining: 3.39s
9:	learn: 0.5355704	total: 34.1ms	remaining: 3.37s
10:	learn: 0.5255939	total: 37.3ms	remaining: 3.35s
11:	learn: 0.5175927	total: 40.5ms	remaining: 3.33s
12:	learn: 0.5078640	total: 43.8ms	remaining: 3.32s
13:	learn: 0.5001078	total: 47ms	remaining: 3.31s
14:	learn: 0.4916880	total: 50.3ms	remaining: 3.3s
15:	learn: 0.4831184	total: 53.5ms	remaining: 3.29s
16:	learn: 0.4768155	total: 56.8ms	remaining: 3.28s
17:	learn: 0.4689931	total: 60ms	remaining: 3.27s
18:	learn: 0.4631053	total: 63.2ms	remaining: 3.26s
19:	learn: 0.4560460	total: 66.4ms	remaining: 3.25s
20:	learn: 0.4519543	total: 68.8ms	remaining: 3.21s
21:	learn: 0.4471517	total: 72.2ms	remaining: 3.21s
22:	learn: 0.4427988	total: 75.4ms	remaining: 3.2s
23:	learn: 0.4372908	total: 78.8ms	remaining: 3.2s
24:	learn: 0.4335456	total: 82.1ms	remaining: 3.2s
25:	learn: 0.4289110	total: 85.4ms	remaining: 3.2s
26:	learn: 0.4253146	total: 88.6ms	remaining: 3.19s
27:	learn: 0.4210658	total: 93.8ms	remaining: 3.25s
28:	learn: 0.4179822	total: 97.2ms	remaining: 3.25s
29:	learn: 0.4144096	total: 100ms	remaining: 3.25s
30:	learn: 0.4114490	total: 104ms	remaining: 3.25s
31:	learn: 0.4080552	total: 107ms	remaining: 3.24s
32:	learn: 0.4048954	total: 110ms	remaining: 3.23s
33:	learn: 0.4022858	total: 114ms	remaining: 3.25s
34:	learn: 0.3993749	total: 118ms	remaining: 3.25s
35:	learn: 0.3961434	total: 121ms	remaining: 3.25s
36:	learn: 0.3934123	total: 124ms	remaining: 3.24s
37:	learn: 0.3908636	total: 130ms	remaining: 3.29s
38:	learn: 0.3887897	total: 134ms	remaining: 3.29s
39:	learn: 0.3863986	total: 137ms	remaining: 3.29s
40:	learn: 0.3845120	total: 141ms	remaining: 3.29s
41:	learn: 0.3824872	total: 147ms	remaining: 3.35s
42:	learn: 0.3806652	total: 150ms	remaining: 3.35s
43:	learn: 0.3787917	total: 154ms	remaining: 3.35s
44:	learn: 0.3765648	total: 157ms	remaining: 3.34s
45:	learn: 0.3748312	total: 161ms	remaining: 3.33s
46:	learn: 0.3730097	total: 164ms	remaining: 3.33s
47:	learn: 0.3718792	total: 167ms	remaining: 3.32s
48:	learn: 0.3703661	total: 170ms	remaining: 3.31s
49:	learn: 0.3692082	total: 174ms	remaining: 3.3s
50:	learn: 0.3679927	total: 177ms	remaining: 3.29s
51:	learn: 0.3670238	total: 180ms	remaining: 3.29s
52:	learn: 0.3658839	total: 184ms	remaining: 3.28s
53:	learn: 0.3644144	total: 187ms	remaining: 3.28s
54:	learn: 0.3634439	total: 191ms	remaining: 3.28s
55:	learn: 0.3622945	total: 198ms	remaining: 3.34s
56:	learn: 0.3608835	total: 202ms	remaining: 3.35s
57:	learn: 0.3600251	total: 206ms	remaining: 3.34s
58:	learn: 0.3590766	total: 209ms	remaining: 3.33s
59:	learn: 0.3581796	total: 213ms	remaining: 3.33s
60:	learn: 0.3569805	total: 216ms	remaining: 3.33s
61:	learn: 0.3557230	total: 219ms	remaining: 3.32s
62:	learn: 0.3547338	total: 223ms	remaining: 3.31s
63:	learn: 0.3541512	total: 226ms	remaining: 3.3s
64:	learn: 0.3532838	total: 229ms	remaining: 3.29s
65:	learn: 0.3526202	total: 232ms	remaining: 3.29s
66:	learn: 0.3519263	total: 236ms	remaining: 3.28s
67:	learn: 0.3512206	total: 239ms	remaining: 3.27s
68:	learn: 0.3504451	total: 242ms	remaining: 3.27s
69:	learn: 0.3498904	total: 246ms	remaining: 3.26s
70:	learn: 0.3493444	total: 249ms	remaining: 3.26s
71:	learn: 0.3486203	total: 252ms	remaining: 3.25s
72:	learn: 0.3482444	total: 255ms	remaining: 3.24s
73:	learn: 0.3475695	total: 258ms	remaining: 3.23s
74:	learn: 0.3473435	total: 261ms	remaining: 3.22s
75:	learn: 0.3466759	total: 264ms	remaining: 3.21s
76:	learn: 0.3460816	total: 268ms	remaining: 3.21s
77:	learn: 0.3456085	total: 271ms	remaining: 3.2s
78:	learn: 0.3451049	total: 274ms	remaining: 3.19s
79:	learn: 0.3443639	total: 277ms	remaining: 3.19s
80:	learn: 0.3438494	total: 281ms	remaining: 3.18s
81:	learn: 0.3435597	total: 284ms	remaining: 3.18s
82:	learn: 0.3431682	total: 287ms	remaining: 3.17s
83:	learn: 0.3426586	total: 290ms	remaining: 3.17s
84:	learn: 0.3422379	total: 294ms	remaining: 3.16s
85:	learn: 0.3417254	total: 297ms	remaining: 3.15s
86:	learn: 0.3410524	total: 300ms	remaining: 3.15s
87:	learn: 0.3407811	total: 303ms	remaining: 3.14s
88:	learn: 0.3403022	total: 307ms	remaining: 3.14s
89:	learn: 0.3398471	total: 310ms	remaining: 3.13s
90:	learn: 0.3392698	total: 313ms	remaining: 3.13s
91:	learn: 0.3389449	total: 316ms	remaining: 3.12s
92:	learn: 0.3387505	total: 320ms	remaining: 3.12s
93:	learn: 0.3383889	total: 323ms	remaining: 3.11s
94:	learn: 0.3379337	total: 327ms	remaining: 3.11s
95:	learn: 0.3373411	total: 332ms	remaining: 3.12s
96:	learn: 0.3367913	total: 335ms	remaining: 3.12s
97:	learn: 0.3364075	total: 338ms	remaining: 3.11s
98:	learn: 0.3361608	total: 341ms	remaining: 3.11s
99:	learn: 0.3358467	total: 346ms	remaining: 3.11s
100:	learn: 0.3355087	total: 350ms	remaining: 3.11s
101:	learn: 0.3352653	total: 353ms	remaining: 3.11s
102:	learn: 0.3348994	total: 356ms	remaining: 3.1s
103:	learn: 0.3346484	total: 359ms	remaining: 3.1s
104:	learn: 0.3343668	total: 363ms	remaining: 3.09s
105:	learn: 0.3340847	total: 366ms	remaining: 3.08s
106:	learn: 0.3338076	total: 369ms	remaining: 3.08s
107:	learn: 0.3335377	total: 373ms	remaining: 3.08s
108:	learn: 0.3330975	total: 376ms	remaining: 3.07s
109:	learn: 0.3327424	total: 379ms	remaining: 3.07s
110:	learn: 0.3324162	total: 383ms	remaining: 3.06s
111:	learn: 0.3319256	total: 386ms	remaining: 3.06s
112:	learn: 0.3316473	total: 389ms	remaining: 3.06s
113:	learn: 0.3313281	total: 393ms	remaining: 3.06s
114:	learn: 0.3309465	total: 397ms	remaining: 3.06s
115:	learn: 0.3307907	total: 400ms	remaining: 3.05s
116:	learn: 0.3305704	total: 403ms	remaining: 3.04s
117:	learn: 0.3303371	total: 407ms	remaining: 3.04s
118:	learn: 0.3300797	total: 410ms	remaining: 3.03s
119:	learn: 0.3297700	total: 413ms	remaining: 3.03s
120:	learn: 0.3296197	total: 416ms	remaining: 3.02s
121:	learn: 0.3293923	total: 420ms	remaining: 3.02s
122:	learn: 0.3291490	total: 423ms	remaining: 3.02s
123:	learn: 0.3287291	total: 426ms	remaining: 3.01s
124:	learn: 0.3285029	total: 430ms	remaining: 3.01s
125:	learn: 0.3282730	total: 433ms	remaining: 3s
126:	learn: 0.3279960	total: 436ms	remaining: 3s
127:	learn: 0.3277859	total: 439ms	remaining: 2.99s
128:	learn: 0.3274514	total: 443ms	remaining: 2.99s
129:	learn: 0.3271191	total: 447ms	remaining: 2.99s
130:	learn: 0.3268063	total: 450ms	remaining: 2.99s
131:	learn: 0.3265125	total: 454ms	remaining: 2.98s
132:	learn: 0.3262868	total: 457ms	remaining: 2.98s
133:	learn: 0.3261051	total: 461ms	remaining: 2.98s
134:	learn: 0.3259006	total: 464ms	remaining: 2.97s
135:	learn: 0.3256199	total: 467ms	remaining: 2.97s
136:	learn: 0.3253531	total: 470ms	remaining: 2.96s
137:	learn: 0.3251805	total: 473ms	remaining: 2.96s
138:	learn: 0.3249804	total: 477ms	remaining: 2.95s
139:	learn: 0.3248502	total: 480ms	remaining: 2.95s
140:	learn: 0.3246710	total: 483ms	remaining: 2.94s
141:	learn: 0.3245435	total: 486ms	remaining: 2.94s
142:	learn: 0.3244152	total: 490ms	remaining: 2.93s
143:	learn: 0.3242826	total: 493ms	remaining: 2.93s
144:	learn: 0.3239489	total: 496ms	remaining: 2.93s
145:	learn: 0.3236905	total: 499ms	remaining: 2.92s
146:	learn: 0.3235449	total: 503ms	remaining: 2.92s
147:	learn: 0.3232491	total: 506ms	remaining: 2.91s
148:	learn: 0.3230522	total: 509ms	remaining: 2.91s
149:	learn: 0.3229131	total: 512ms	remaining: 2.9s
150:	learn: 0.3227963	total: 516ms	remaining: 2.9s
151:	learn: 0.3225008	total: 519ms	remaining: 2.89s
152:	learn: 0.3222845	total: 523ms	remaining: 2.89s
153:	learn: 0.3221100	total: 528ms	remaining: 2.9s
154:	learn: 0.3219930	total: 532ms	remaining: 2.9s
155:	learn: 0.3218107	total: 536ms	remaining: 2.9s
156:	learn: 0.3214941	total: 539ms	remaining: 2.89s
157:	learn: 0.3212881	total: 543ms	remaining: 2.9s
158:	learn: 0.3211425	total: 547ms	remaining: 2.89s
159:	learn: 0.3210393	total: 550ms	remaining: 2.89s
160:	learn: 0.3208873	total: 554ms	remaining: 2.88s
161:	learn: 0.3208107	total: 557ms	remaining: 2.88s
162:	learn: 0.3205866	total: 560ms	remaining: 2.88s
163:	learn: 0.3204446	total: 563ms	remaining: 2.87s
164:	learn: 0.3202029	total: 566ms	remaining: 2.87s
165:	learn: 0.3199559	total: 570ms	remaining: 2.86s
166:	learn: 0.3197973	total: 573ms	remaining: 2.86s
167:	learn: 0.3196751	total: 576ms	remaining: 2.85s
168:	learn: 0.3195018	total: 580ms	remaining: 2.85s
169:	learn: 0.3193890	total: 583ms	remaining: 2.85s
170:	learn: 0.3191730	total: 586ms	remaining: 2.84s
171:	learn: 0.3189735	total: 591ms	remaining: 2.85s
172:	learn: 0.3187535	total: 595ms	remaining: 2.84s
173:	learn: 0.3185208	total: 598ms	remaining: 2.84s
174:	learn: 0.3183282	total: 602ms	remaining: 2.84s
175:	learn: 0.3181973	total: 605ms	remaining: 2.83s
176:	learn: 0.3180266	total: 608ms	remaining: 2.83s
177:	learn: 0.3178766	total: 612ms	remaining: 2.83s
178:	learn: 0.3176815	total: 615ms	remaining: 2.82s
179:	learn: 0.3175019	total: 618ms	remaining: 2.82s
180:	learn: 0.3172833	total: 622ms	remaining: 2.81s
181:	learn: 0.3169756	total: 625ms	remaining: 2.81s
182:	learn: 0.3168287	total: 629ms	remaining: 2.81s
183:	learn: 0.3167025	total: 632ms	remaining: 2.8s
184:	learn: 0.3165331	total: 635ms	remaining: 2.8s
185:	learn: 0.3164163	total: 639ms	remaining: 2.79s
186:	learn: 0.3161594	total: 642ms	remaining: 2.79s
187:	learn: 0.3159845	total: 645ms	remaining: 2.79s
188:	learn: 0.3158351	total: 649ms	remaining: 2.78s
189:	learn: 0.3156747	total: 652ms	remaining: 2.78s
190:	learn: 0.3155449	total: 656ms	remaining: 2.78s
191:	learn: 0.3153438	total: 659ms	remaining: 2.77s
192:	learn: 0.3152203	total: 662ms	remaining: 2.77s
193:	learn: 0.3151238	total: 666ms	remaining: 2.77s
194:	learn: 0.3149809	total: 669ms	remaining: 2.76s
195:	learn: 0.3147883	total: 672ms	remaining: 2.76s
196:	learn: 0.3145787	total: 675ms	remaining: 2.75s
197:	learn: 0.3144956	total: 679ms	remaining: 2.75s
198:	learn: 0.3142527	total: 682ms	remaining: 2.75s
199:	learn: 0.3140524	total: 685ms	remaining: 2.74s
200:	learn: 0.3139042	total: 690ms	remaining: 2.74s
201:	learn: 0.3138202	total: 695ms	remaining: 2.75s
202:	learn: 0.3136472	total: 699ms	remaining: 2.74s
203:	learn: 0.3134617	total: 702ms	remaining: 2.74s
204:	learn: 0.3132125	total: 705ms	remaining: 2.73s
205:	learn: 0.3131188	total: 709ms	remaining: 2.73s
206:	learn: 0.3129787	total: 712ms	remaining: 2.73s
207:	learn: 0.3128252	total: 715ms	remaining: 2.72s
208:	learn: 0.3126968	total: 720ms	remaining: 2.72s
209:	learn: 0.3125953	total: 723ms	remaining: 2.72s
210:	learn: 0.3125118	total: 727ms	remaining: 2.72s
211:	learn: 0.3123346	total: 730ms	remaining: 2.71s
212:	learn: 0.3121932	total: 734ms	remaining: 2.71s
213:	learn: 0.3120591	total: 737ms	remaining: 2.71s
214:	learn: 0.3119670	total: 742ms	remaining: 2.71s
215:	learn: 0.3118547	total: 746ms	remaining: 2.71s
216:	learn: 0.3116765	total: 749ms	remaining: 2.7s
217:	learn: 0.3115491	total: 753ms	remaining: 2.7s
218:	learn: 0.3114707	total: 756ms	remaining: 2.69s
219:	learn: 0.3113524	total: 759ms	remaining: 2.69s
220:	learn: 0.3112488	total: 762ms	remaining: 2.69s
221:	learn: 0.3111220	total: 766ms	remaining: 2.68s
222:	learn: 0.3109370	total: 769ms	remaining: 2.68s
223:	learn: 0.3107782	total: 772ms	remaining: 2.67s
224:	learn: 0.3105715	total: 775ms	remaining: 2.67s
225:	learn: 0.3104623	total: 779ms	remaining: 2.67s
226:	learn: 0.3101759	total: 782ms	remaining: 2.66s
227:	learn: 0.3100437	total: 786ms	remaining: 2.66s
228:	learn: 0.3099178	total: 791ms	remaining: 2.66s
229:	learn: 0.3097747	total: 794ms	remaining: 2.66s
230:	learn: 0.3096557	total: 798ms	remaining: 2.66s
231:	learn: 0.3094765	total: 802ms	remaining: 2.65s
232:	learn: 0.3093368	total: 805ms	remaining: 2.65s
233:	learn: 0.3091317	total: 809ms	remaining: 2.65s
234:	learn: 0.3088861	total: 813ms	remaining: 2.65s
235:	learn: 0.3086639	total: 816ms	remaining: 2.64s
236:	learn: 0.3085698	total: 820ms	remaining: 2.64s
237:	learn: 0.3084478	total: 824ms	remaining: 2.64s
238:	learn: 0.3082774	total: 827ms	remaining: 2.63s
239:	learn: 0.3081885	total: 834ms	remaining: 2.64s
240:	learn: 0.3080302	total: 842ms	remaining: 2.65s
241:	learn: 0.3077834	total: 851ms	remaining: 2.66s
242:	learn: 0.3076692	total: 859ms	remaining: 2.68s
243:	learn: 0.3075321	total: 865ms	remaining: 2.68s
244:	learn: 0.3074564	total: 869ms	remaining: 2.68s
245:	learn: 0.3073048	total: 872ms	remaining: 2.67s
246:	learn: 0.3071184	total: 875ms	remaining: 2.67s
247:	learn: 0.3070345	total: 878ms	remaining: 2.66s
248:	learn: 0.3068458	total: 882ms	remaining: 2.66s
249:	learn: 0.3066840	total: 885ms	remaining: 2.65s
250:	learn: 0.3066152	total: 888ms	remaining: 2.65s
251:	learn: 0.3064308	total: 891ms	remaining: 2.65s
252:	learn: 0.3062118	total: 895ms	remaining: 2.64s
253:	learn: 0.3060801	total: 898ms	remaining: 2.64s
254:	learn: 0.3059686	total: 901ms	remaining: 2.63s
255:	learn: 0.3058678	total: 904ms	remaining: 2.63s
256:	learn: 0.3057622	total: 908ms	remaining: 2.62s
257:	learn: 0.3056279	total: 911ms	remaining: 2.62s
258:	learn: 0.3054369	total: 914ms	remaining: 2.62s
259:	learn: 0.3052324	total: 920ms	remaining: 2.62s
260:	learn: 0.3050810	total: 924ms	remaining: 2.62s
261:	learn: 0.3049798	total: 927ms	remaining: 2.61s
262:	learn: 0.3048948	total: 930ms	remaining: 2.61s
263:	learn: 0.3047449	total: 934ms	remaining: 2.6s
264:	learn: 0.3045848	total: 937ms	remaining: 2.6s
265:	learn: 0.3044767	total: 942ms	remaining: 2.6s
266:	learn: 0.3043667	total: 945ms	remaining: 2.6s
267:	learn: 0.3042303	total: 949ms	remaining: 2.59s
268:	learn: 0.3041600	total: 952ms	remaining: 2.59s
269:	learn: 0.3040200	total: 955ms	remaining: 2.58s
270:	learn: 0.3038557	total: 959ms	remaining: 2.58s
271:	learn: 0.3037207	total: 962ms	remaining: 2.57s
272:	learn: 0.3035793	total: 965ms	remaining: 2.57s
273:	learn: 0.3034059	total: 968ms	remaining: 2.56s
274:	learn: 0.3033105	total: 972ms	remaining: 2.56s
275:	learn: 0.3031823	total: 975ms	remaining: 2.56s
276:	learn: 0.3030290	total: 978ms	remaining: 2.55s
277:	learn: 0.3029346	total: 982ms	remaining: 2.55s
278:	learn: 0.3027511	total: 988ms	remaining: 2.55s
279:	learn: 0.3025511	total: 991ms	remaining: 2.55s
280:	learn: 0.3024412	total: 994ms	remaining: 2.54s
281:	learn: 0.3023140	total: 998ms	remaining: 2.54s
282:	learn: 0.3021296	total: 1s	remaining: 2.54s
283:	learn: 0.3019914	total: 1s	remaining: 2.53s
284:	learn: 0.3018993	total: 1.01s	remaining: 2.53s
285:	learn: 0.3017173	total: 1.01s	remaining: 2.52s
286:	learn: 0.3015766	total: 1.01s	remaining: 2.52s
287:	learn: 0.3014070	total: 1.02s	remaining: 2.51s
288:	learn: 0.3012759	total: 1.02s	remaining: 2.51s
289:	learn: 0.3011097	total: 1.02s	remaining: 2.51s
290:	learn: 0.3010027	total: 1.03s	remaining: 2.5s
291:	learn: 0.3009027	total: 1.03s	remaining: 2.5s
292:	learn: 0.3008018	total: 1.03s	remaining: 2.49s
293:	learn: 0.3007109	total: 1.04s	remaining: 2.49s
294:	learn: 0.3005919	total: 1.04s	remaining: 2.48s
295:	learn: 0.3004746	total: 1.04s	remaining: 2.48s
296:	learn: 0.3003510	total: 1.05s	remaining: 2.48s
297:	learn: 0.3001952	total: 1.05s	remaining: 2.47s
298:	learn: 0.3001200	total: 1.05s	remaining: 2.47s
299:	learn: 0.2999120	total: 1.06s	remaining: 2.46s
300:	learn: 0.2998344	total: 1.06s	remaining: 2.46s
301:	learn: 0.2997381	total: 1.06s	remaining: 2.46s
302:	learn: 0.2995978	total: 1.07s	remaining: 2.46s
303:	learn: 0.2994721	total: 1.07s	remaining: 2.45s
304:	learn: 0.2993864	total: 1.07s	remaining: 2.45s
305:	learn: 0.2992999	total: 1.08s	remaining: 2.44s
306:	learn: 0.2992447	total: 1.08s	remaining: 2.44s
307:	learn: 0.2991183	total: 1.08s	remaining: 2.44s
308:	learn: 0.2990340	total: 1.09s	remaining: 2.43s
309:	learn: 0.2989403	total: 1.09s	remaining: 2.43s
310:	learn: 0.2988278	total: 1.09s	remaining: 2.42s
311:	learn: 0.2986574	total: 1.1s	remaining: 2.42s
312:	learn: 0.2985282	total: 1.1s	remaining: 2.42s
313:	learn: 0.2984283	total: 1.1s	remaining: 2.41s
314:	learn: 0.2982951	total: 1.11s	remaining: 2.41s
315:	learn: 0.2982206	total: 1.11s	remaining: 2.41s
316:	learn: 0.2981029	total: 1.12s	remaining: 2.41s
317:	learn: 0.2980244	total: 1.12s	remaining: 2.41s
318:	learn: 0.2979171	total: 1.13s	remaining: 2.4s
319:	learn: 0.2978098	total: 1.13s	remaining: 2.4s
320:	learn: 0.2976923	total: 1.13s	remaining: 2.39s
321:	learn: 0.2975583	total: 1.14s	remaining: 2.4s
322:	learn: 0.2973901	total: 1.14s	remaining: 2.39s
323:	learn: 0.2971830	total: 1.14s	remaining: 2.39s
324:	learn: 0.2970554	total: 1.15s	remaining: 2.38s
325:	learn: 0.2970049	total: 1.15s	remaining: 2.38s
326:	learn: 0.2968802	total: 1.15s	remaining: 2.38s
327:	learn: 0.2967541	total: 1.16s	remaining: 2.37s
328:	learn: 0.2966427	total: 1.16s	remaining: 2.37s
329:	learn: 0.2965347	total: 1.16s	remaining: 2.36s
330:	learn: 0.2964521	total: 1.17s	remaining: 2.36s
331:	learn: 0.2963007	total: 1.17s	remaining: 2.36s
332:	learn: 0.2962063	total: 1.17s	remaining: 2.35s
333:	learn: 0.2960872	total: 1.18s	remaining: 2.35s
334:	learn: 0.2958972	total: 1.18s	remaining: 2.34s
335:	learn: 0.2958338	total: 1.19s	remaining: 2.34s
336:	learn: 0.2957293	total: 1.19s	remaining: 2.34s
337:	learn: 0.2956451	total: 1.19s	remaining: 2.34s
338:	learn: 0.2954719	total: 1.2s	remaining: 2.33s
339:	learn: 0.2953275	total: 1.2s	remaining: 2.33s
340:	learn: 0.2952251	total: 1.2s	remaining: 2.33s
341:	learn: 0.2950779	total: 1.21s	remaining: 2.32s
342:	learn: 0.2949292	total: 1.21s	remaining: 2.32s
343:	learn: 0.2948127	total: 1.21s	remaining: 2.31s
344:	learn: 0.2947257	total: 1.22s	remaining: 2.31s
345:	learn: 0.2945858	total: 1.22s	remaining: 2.3s
346:	learn: 0.2944517	total: 1.22s	remaining: 2.3s
347:	learn: 0.2943965	total: 1.23s	remaining: 2.3s
348:	learn: 0.2943426	total: 1.23s	remaining: 2.29s
349:	learn: 0.2942816	total: 1.23s	remaining: 2.29s
350:	learn: 0.2942177	total: 1.24s	remaining: 2.28s
351:	learn: 0.2940967	total: 1.24s	remaining: 2.28s
352:	learn: 0.2939608	total: 1.24s	remaining: 2.28s
353:	learn: 0.2938818	total: 1.25s	remaining: 2.27s
354:	learn: 0.2937620	total: 1.25s	remaining: 2.27s
355:	learn: 0.2936378	total: 1.25s	remaining: 2.26s
356:	learn: 0.2934827	total: 1.25s	remaining: 2.26s
357:	learn: 0.2933874	total: 1.26s	remaining: 2.26s
358:	learn: 0.2932281	total: 1.26s	remaining: 2.25s
359:	learn: 0.2930803	total: 1.26s	remaining: 2.25s
360:	learn: 0.2929174	total: 1.27s	remaining: 2.24s
361:	learn: 0.2928498	total: 1.27s	remaining: 2.24s
362:	learn: 0.2927283	total: 1.27s	remaining: 2.24s
363:	learn: 0.2926097	total: 1.28s	remaining: 2.23s
364:	learn: 0.2925008	total: 1.28s	remaining: 2.23s
365:	learn: 0.2923368	total: 1.28s	remaining: 2.22s
366:	learn: 0.2921647	total: 1.29s	remaining: 2.22s
367:	learn: 0.2920795	total: 1.29s	remaining: 2.22s
368:	learn: 0.2920064	total: 1.29s	remaining: 2.21s
369:	learn: 0.2919021	total: 1.3s	remaining: 2.21s
370:	learn: 0.2917926	total: 1.3s	remaining: 2.21s
371:	learn: 0.2916399	total: 1.3s	remaining: 2.2s
372:	learn: 0.2915501	total: 1.31s	remaining: 2.2s
373:	learn: 0.2914137	total: 1.31s	remaining: 2.2s
374:	learn: 0.2912957	total: 1.32s	remaining: 2.19s
375:	learn: 0.2911641	total: 1.32s	remaining: 2.19s
376:	learn: 0.2910280	total: 1.32s	remaining: 2.19s
377:	learn: 0.2909312	total: 1.33s	remaining: 2.18s
378:	learn: 0.2907971	total: 1.33s	remaining: 2.18s
379:	learn: 0.2906833	total: 1.33s	remaining: 2.17s
380:	learn: 0.2905895	total: 1.34s	remaining: 2.17s
381:	learn: 0.2904271	total: 1.34s	remaining: 2.17s
382:	learn: 0.2903127	total: 1.34s	remaining: 2.17s
383:	learn: 0.2902134	total: 1.35s	remaining: 2.16s
384:	learn: 0.2901700	total: 1.35s	remaining: 2.16s
385:	learn: 0.2900242	total: 1.35s	remaining: 2.16s

In [136]:
y_pred = model_10.predict(x_test)

In [137]:
print(confusion_matrix(y_test, y_pred))

[[1540   67]
 [ 199  194]]

In [138]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.89      0.96      0.92      1607
           1       0.74      0.49      0.59       393

    accuracy                           0.87      2000
   macro avg       0.81      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

In [139]:
model_11.fit(x_train, y_train)

[LightGBM] [Info] Number of positive: 1644, number of negative: 6356
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001815 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 854
[LightGBM] [Info] Number of data points in the train set: 8000, number of used features: 10
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.205500 -> initscore=-1.352267
[LightGBM] [Info] Start training from score -1.352267

LGBMClassifier()

In [140]:
y_pred = model_11.predict(x_test)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

In [141]:
print(confusion_matrix(y_test, y_pred))

[[1531   76]
 [ 200  193]]

In [142]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      0.95      0.92      1607
           1       0.72      0.49      0.58       393

    accuracy                           0.86      2000
   macro avg       0.80      0.72      0.75      2000
weighted avg       0.85      0.86      0.85      2000

In [143]:
models = [model_1, model_2, model_3, model_4, model_5,
          model_6, model_7, model_8, model_9, model_10, model_11]
models_names = ['LogisticRegression', 'SVC', 'KNeighborsClassifier', 'DecisionTreeClassifier',
                'RandomForestClassifier', 'BaggingClassifier', 'ExtraTreesClassifier', 'AdaBoostClassifier',
                'XGBClassifier', 'CatBoostClassifier', 'LGBMClassifier']

train_score = [model.score(x_train, y_train) for model in models]
test_score = [model.score(x_test, y_test) for model in models]

ratio = []
for train, test in zip(train_score, test_score):
    result = train - test
    ratio.append(f'{result * 100:.2f}%')

rate = []
for train, test in zip(train_score, test_score):
    if train <= 0.65 and test <= 0.65:
        rate.append('bad')
    elif train > test * 1.10 or train >= 1.00:
        rate.append('overfit')
    elif train > 0.65 and train < 0.80 and test > 0.65 and test < 0.80:
        rate.append('middle')
    elif train >= 0.80 and test >= 0.80 and train < 1.00 and test < 1.00:
        rate.append('good')
    elif train >= 0.80 and test < 0.80:
        rate.append('high train, low test')
    else:
        rate.append('unknown')
model_score = pd.DataFrame({
    'Model': models_names,
    'Train score': [f'{round(score * 100, 2)}%' for score in train_score],
    'Test score': [f'{round(score * 100, 2)}%' for score in test_score],
    'Ratio difference': ratio,
    'Evaluate model': rate,
})

model_score

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

,Model,Train score,Test score,Ratio difference,Evaluate model
0,LogisticRegression,80.86%,81.6%,-0.74%,good
1,SVC,85.66%,85.3%,0.36%,good
2,KNeighborsClassifier,86.51%,82.4%,4.11%,good
3,DecisionTreeClassifier,100.0%,78.75%,21.25%,overfit
4,RandomForestClassifier,100.0%,86.85%,13.15%,overfit
5,BaggingClassifier,98.36%,85.85%,12.51%,overfit
6,ExtraTreesClassifier,100.0%,86.7%,13.30%,overfit
7,AdaBoostClassifier,85.41%,85.8%,-0.39%,good
8,XGBClassifier,95.47%,85.55%,9.92%,overfit
9,CatBoostClassifier,90.8%,86.7%,4.10%,good
10,LGBMClassifier,91.39%,86.2%,5.19%,good